CREATE TABLE `fuel_charges_import_v2` (
  `pk` int(11) NOT NULL AUTO_INCREMENT,
  `seq_no` int(11) NOT NULL DEFAULT 0,
  `supplier_id` int(11) NOT NULL DEFAULT 0,
  `card_no` varchar(50) DEFAULT NULL,
  `ddate` datetime DEFAULT NULL,
  `reg_no` varchar(50) DEFAULT NULL,
  `charge_type` varchar(50) DEFAULT NULL,
  `price_per_liter` double DEFAULT NULL,
  `litres` double DEFAULT NULL,
  `total_price` double DEFAULT NULL,
  `total_vat` double DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `station` varchar(200) DEFAULT NULL,
  `order_no` varchar(50) DEFAULT NULL,
  `charge_code` varchar(10) DEFAULT NULL,
  `mileage` int(11) DEFAULT NULL,
  `is_replicated` int(11) NOT NULL DEFAULT 0,
  `product_type_id` int(11) NOT NULL DEFAULT 0,
  `charge_type_id` int(11) NOT NULL DEFAULT 0,
  `userid` int(11) DEFAULT NULL,
  `data` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`pk`)
) DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;